version: '2.1'

networks:
  mo_net:
    name: mo_net
 
services:
  firebird:
    container_name: firebird
    restart: always
    image: jacobalberty/firebird:2.5.9-sc
    networks:
      - mo_net
    ports:
      - 3050:3050
      - 3070:3070
    volumes:
      - /mirokon/docker/volume/firebird:/firebird
    environment:
      - TZ=Europe/Moscow
      - ISC_PASSWORD=masterkey
